image: gradle:jdk11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: gradle build -x test
  allow_failure: false

delombok:
  stage: prepare
  script:
    - gradle delombok
  artifacts:
    paths:
      - build/delombok/**

test:
  stage: test
  script:
    - gradle test printCoverage
  coverage: '/^Coverage:\s(\d+\.\d+%)/'
  artifacts:
    paths:
      - build/reports/jacoco
