image: gradle:jdk11

stages:
  - build
  - test
  - junit

build:
  stage: build
  script: gradle build -x test
  allow_failure: false

test:
  stage: test
  script: gradle test

junit:
  stage: test
  script:
    - gradle test printCoverage
  coverage: '/^Coverage:\s(\d+\.\d+%)/'
  when: on_success
  artifacts:
    paths:
      - build/reports/jacoco/
    reports:
      junit: build/test-results/test/**.xml

pages:
  stage: junit
  dependencies:
    - junit
  script:
    - mkdir public
    - mv build/reports/jacoco/test/html/index.html public
  artifacts:
    paths:
      - public
  only:
    - master
