image: gradle:jdk11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: gradle build -x test
  allow_failure: false


delombok:
  stage: build
  script: gradle delombok
  artifacts:
    paths:
      - build/delombok/**

test:
  stage: test
  script:
    - gradle test
  coverage: '/^Coverage:\s(\d+\.\d+%)/'
  artifacts:
    paths:
      - build/reports/jacoco

deploy:
  stage: deploy
  script:
    - gradle jar
  artifacts:
    paths:
      - build/libs/*.jar
  when: manual
