image: gradle:jdk11

stages:
  - build
  - test

build:
  stage: build
  script: gradle build -x test
  allow_failure: false

test:
  stage: test
  script: gradle test

junit:
  stage: test
  dependencies:
    - compile
  script:
    - gradle test printCoverage
  coverage: '\(\d+.\d+\%\) covered'
  when: on_success
  artifacts:
    paths:
      - build/reports/jacoco/
    reports:
      junit: build/test-results/test/**.xml
