image: gradle:jdk11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: gradle build -x test
  allow_failure: false

test:
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - build/reports/jacoco
