image: gradle:jdk11

stages:
  - build
  - prepare
  - test
  - deploy

build:
  stage: build
  script:
    - gradle jar
  allow_failure: false
  artifacts:
    paths:
      - build/libs/*.jar
  when: manual

delombok:
  stage: prepare
  script:
    - gradle delombok
  artifacts:
    paths:
      - build/delombok/**

test:
  stage: test
  script:
    - gradle test printCoverage
  coverage: '/^Coverage:\s(\d+\.\d+%)/'
  artifacts:
    paths:
      - build/reports/jacoco
