image: gradle:jdk11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: gradle build -x test
  allow_failure: false

test:
  stage: test
  script:
    - gradle test printCoverage
  when: on_success
  artifacts:
    paths:
      - build/reports/jacoco/



pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir public
    - mv build/reports/jacoco/test/html/index.html public
  artifacts:
    paths:
      - public
  only:
    - master
